- name: BIRD
  hosts: all
  sudo: true
  handlers:
  - name: restart bird4
    service: name=bird state=restarted enabled=yes
  - name: reload bird4
    service: name=bird state=reloaded enabled=yes
  - name: restart bird6
    service: name=bird6 state=stopped enabled=yes
  - name: reload bird6
    service: name=bird6 state=stopped enabled=yes

  tasks:
  - set_fact:
      bird4_config: /usr/local/etc/bird.conf
      bird6_config: /usr/local/etc/bird6.conf
    when: ansible_distribution == 'FreeBSD'
  - set_fact:
      bird4_config: /etc/bird/bird.conf
      bird6_config: /etc/bird/bird6.conf
    when: ansible_distribution == 'Debian'

  - name: Install bird (Debian)
    when: ansible_distribution == 'Debian'
    apt: name=bird state=latest force=yes
    notify: restart bird4
    notify: restart bird6
  - name: Install bird4 (FreeBSD)
    when: ansible_distribution == 'FreeBSD'
    pkgng: name=bird state=present
    notify: restart bird4
  - name: Install bird6 (FreeBSD)
    when: ansible_distribution == 'FreeBSD'
    pkgng: name=bird6 state=present
    notify: restart bird6

  - name: Paste bird4 config
    template: >
      src=templates/bird4.conf
      dest={{ bird4_config }}
      mode=0744
    notify: reload bird4
  - name: Paste bird6 config
    template: >
      src=templates/bird6.conf
      dest={{ bird6_config }}
      mode=0744
    notify: reload bird6
